### PR TITLE
Implement droplet shutdown

### PR DESCRIPTION
**Pull request by 01sas**
A recommended way to turn droplet off on DigitalOcean is to use shutdown which is not available in this plugin.

### CODE REVIEW

**Comment by rmoriz** [comment]
Can you add tests? It's a new API call so we should really check it. Thanks

nb: please rebase from master, I've fixed the CI error that travis was reporting (unrelated to your PR)

**Comment by 01sas** [comment]
I added tests. Sorry for so long reply.

**Comment by 01sas** [comment]
I also has a question to you. We need to have support for batch operations. Like creating several droplets at the same time. Is there any plans from you to support such batching?

**Comment by rmoriz** [comment]
Sorry, didn't see your PR :(

**Comment by rmoriz** [comment]
Batch requests: I think this is out of scope for this project. Either you want to use shell scripting, or tools like [chef-provisioning](https://github.com/chef/chef-provisioning) or [terraform](https://terraform.io).

**Pull request merged**
