### PR TITLE
my Dockerfile 

### PR DESCRIPTION
**Pull request by kevit**
Useful to manage hostile environments, you just need a docker on your box to start use this plugin

### CODE REVIEW

**Comment by rmoriz** [comment]
What exactly do you mean with "hostile environments"? Actually I don't see a real use case for this…

**Comment by kevit** [comment]
That is a real life example, I have a my own knife.rb on usb stick, but I forgot my laptop. I have a Docker and I just need create bunch of droplets. I just need any device with docker (can be OSx even Windows), then I build this container and can manipulate my DO installation on the way by calling docker run knife with parameters. You should try this way, classic unix-way on the next level)

**Comment by kevit** [comment]
Moreover, you even can pipe bunch of docker containers)

**Comment by rmoriz** [comment]
ChefDK runs on Linux, OSX, Windows, too. And it doesn't need a VirtualBox VM…

**Pull request closed without merging**
