### PR TITLE
merge ZeroBootstrap options.

### PR DESCRIPTION
**Pull request by sawanoboly**
for #79 

- load options from ZeroBootstrap when defined.

### CODE REVIEW

**Comment by daften** [comment]
I need this patch, can a new version of the gem be released? :)

Thanks

**Comment by rmoriz** [comment]
is master working for you?

**Comment by daften** [comment]
yeah, but i need to manually patch files instead of a simple chef gem install.. :)

**Comment by rmoriz** [comment]
2.5.0 is now released

**Comment by daften** [comment]
Thanks so much! :)

**Pull request merged**
